---
install_packages:
  - arp-scan
  - baobab
  - bash-completion
  - borgbackup
  - blender
  - chrome-gnome-shell
  - ffmpeg
  - fping
  - git
  - gnome-extensions-app
  - gnome-tweaks
  - golang
  - htop
  - keepassxc
  - ImageMagick
  - lm_sensors
  - mplayer
  - mpv
  - neofetch
  - nethogs
  - newsboat
  - nmap
  - obs-studio
  - pcmanfm
  - python3-devel
  - python3-streamlink
  - python3-psutil
  - rkhunter
  - rsync
  - sshfs
  - stow
  - syncthing
  - texlive
  - texlive-preprint
  - texstudio
  - tlp
  - tmux 
  - units
  - unrar
  - vim
  - '@Virtualization'
  - virt-manager
  - vlc
  - wireshark
  - youtube-dl

remove_packages:
  - PackageKit
  - PackageKit-glib
  - PackageKit-gstreamer-plugin
  - PackageKit-gtk3-module
  - cheese
  - fedora-logos-httpd
  - gamemode
  - gnome-getting-started-docs
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-horizontal-workspaces
  - gnome-shell-extension-places-menu
  - gnome-online-miners
  - gnome-boxes
  - gnome-initial-setup
  - gnome-software
  - gnome-tour
  - gnome-user-docs
  - gnome-user-share
  - httpd
  - httpd-filesystem
  - httpd-tools
  - mod_dnssd
  - mod_http2
  - libtracker-miner
  - libzapojit
  - tracker
  - ttmkfdir

flatpaks:
  - com.discordapp.Discord
  - com.spotify.Client
  - com.mattermost.Desktop
