- name: get local user name
  command: whoami
  changed_when: false
  become: false
  register: whoami

- name: remove default directories
  file:
    state: absent
    path: "/home/{{ whoami.stdout }}/{{ item }}"
  loop:
    -  "Public"
    - "Templates"
- name: gather service facts
  service_facts:

- name: use NetworkManager for DNS
  block:
    - name: disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
        masked: yes

    - name: remove /etc/resolv.conf symlink
      file:
        path: /etc/resolv.conf
        state: absent

    - name: replace line in NetworkManager.conf
      replace:
        path: /etc/NetworkManager/NetworkManager.conf
        regexp: '#dns=default'
        replace: 'dns=default'

    - name: restart network manager
      systemd:
        name: NetworkManager
        state: restarted
  when: ansible_facts.services['systemd-resolved.service'].state != 'inactive' and ansible_facts.services['systemd-resolved.service'].status != 'masked'

- name: disable & mask polkit
  systemd:
    name: polkit
    state: stopped
    enabled: no
    masked: yes

- name: make bash completion case insensitive
  lineinfile:
    path: /etc/inputrc
    line: "set completion-ignore-case On"
